### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module 

### ISSUE THREAD

**Issue by Skycle** [cipchk/angular-web-storage#1]
ERROR in Error: Metadata version mismatch for module ......./node_modules/angular-web-storage/index.d.ts, found version 4, expected 3, resolving symbol AppModule in ....../src/app/components/app.module.ts, resolving symbol AppModule in ....../src/app/components/app.module.ts
    at Error (native)
    at syntaxError (/mnt/sparkpon/node_modules/_@angular_compiler@4.4.6@@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/mnt/sparkpon/node_modules/_@angular_compiler@4.4.6@@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/mnt/sparkpon/node_modules/_@angular_compiler@4.4.6@@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/mnt/sparkpon/node_modules/_@angular_compiler@4.4.6@@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/mnt/sparkpon/node_modules/_@angular_compiler-cli@4.4.6@@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/mnt/sparkpon/node_modules/_@angular_compiler-cli@4.4.6@@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/mnt/sparkpon/node_modules/_@angular_compiler-cli@4.4.6@@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/mnt/sparkpon/node_modules/_@angular_compiler-cli@4.4.6@@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/mnt/sparkpon/node_modules/_@ngtools_webpack@1.7.4@@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/mnt/sparkpon/node_modules/_@ngtools_webpack@1.7.4@@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by cipchk** [comment]
if you using `1.0.1` version of angular5 project, if not using `1.0.0` version.

**Comment by Skycle** [comment]
angular4用的1.0.0版本，突然出现这个问题，npm start报错，不明白机会原因。

**Comment by cipchk** [comment]
请提供一下你的 `package.json`。

**Comment by Skycle** [comment]
{
  "name": "sparkpon",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.0.20",
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-web-storage": "^1.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "file-loader": "^1.1.5",
    "jquery": "^3.2.1",
    "light7": "^0.4.3",
    "rxjs": "^5.4.2",
    "ts-helpers": "^1.1.1",
    "webpack": "^3.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.7",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/bootstrap": "^3.3.36",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

**Comment by Skycle** [comment]
`{
  "name": "sparkpon",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.0.20",
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-web-storage": "^1.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "file-loader": "^1.1.5",
    "jquery": "^3.2.1",
    "light7": "^0.4.3",
    "rxjs": "^5.4.2",
    "ts-helpers": "^1.1.1",
    "webpack": "^3.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.7",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/bootstrap": "^3.3.36",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
`

**Comment by Skycle** [comment]
```
{
  "name": "sparkpon",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.0.20",
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-web-storage": "^1.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "file-loader": "^1.1.5",
    "jquery": "^3.2.1",
    "light7": "^0.4.3",
    "rxjs": "^5.4.2",
    "ts-helpers": "^1.1.1",
    "webpack": "^3.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.7",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/bootstrap": "^3.3.36",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

```

**Comment by cipchk** [comment]
change to:

```
"angular-web-storage": "1.0.0",
```
