### ISSUE TITLE
Angular 11 support?

### ISSUE THREAD

**Issue by ddurham2** [cipchk/angular-web-storage#13]

**Comment by cipchk** [comment]
Will there be any problems under angular11?

**Comment by ddurham2** [comment]
I was having trouble with it, but figured out my own user error.  So far things are working.  But I'm only using the simplest form of @LocalStorage().  

As a side note, it is not mentioned on the readme.MD (or npm repo page) to 
```
   import { AngularWebStorageModule, } from 'angular-web-storage';
   ...
```
Perhaps that obvious to everyone else, but it was part of my original mistake.


feel free to close
