### ISSUE TITLE
批量删除类似的 key

### ISSUE THREAD

**Issue by tucke** [cipchk/angular-web-storage#2]
能否支持指定一个正则表达式，删除符合该正则的 key；
如，localStroage.remove("BMap_*") 可以删除 BMap_tile_hkwihw 、BMap_symbol_cbomyq 等所有以 BMap_ 开头的key

**Comment by cipchk** [comment]
好建议

**Comment by cipchk** [comment]
localStroage 并没有一个用于获取所有 key 的方法，因此这个功能没办法处理。

**Comment by tucke** [comment]
可否通过，从0开始遍历，一直遍历到结果为 null 为止
![image](https://user-images.githubusercontent.com/16501645/34283399-70b2a790-e706-11e7-828f-3b2777cfc8ea.png)

**Comment by cipchk** [comment]
在不清楚总量的情况下，这种方式也是没有意义。我再思考一下。

**Comment by cipchk** [comment]
的确可以，非常好。
