### ISSUE TITLE
作者版本更新到angularjs5，好像angularjs4就有问题了

### ISSUE THREAD

**Issue by keenw** [cipchk/angular-web-storage#3]
ERROR in Error: Metadata version mismatch for module /node_modules/angular-web-storage/core/service.d.ts, found version 4, expected
3, resolving symbol AngularWebStorageModule in /node
_modules/angular-web-storage/index.d.ts, resolving symbol AngularWebStorageModul
e in /node_modules/angular-web-storage/index.d.ts。

version不匹配了。
而且没找到之前的release版本啊

**Comment by cipchk** [comment]
angular4 请使用 `1.0.0` 版本
