### ISSUE TITLE
With angular 6 is suddenl yet an error in the webstorage module

### ISSUE THREAD

**Issue by jcompagner** [cipchk/angular-web-storage#4]
it is this:

ERROR in angular-web-storage\index.ts(7,2): Error during template compile of 'AngularWebStorageModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

if i google around i do get some hits that looks like that. But still if i look at your source it seems very simple and straighforward so not sure what is wrong here..

Do you have any idea?

**Comment by jcompagner** [comment]
hmm i made a simple example, adjusting yours:

https://stackblitz.com/edit/angular-web-storage-hcre2x

to use the latest angular and also upped the rest, then it also did work

**Comment by cipchk** [comment]
coming soon

**Comment by jcompagner** [comment]
you know what is going wrong?

if removed everything on our project for the web-storage

and if i only include one line of import:

import { LocalStorageService } from 'angular-web-storage/src/service';

then i also get it again, but then a bit different:

ERROR in angular-web-storage\src\service.ts(41,2): Error during template compile of 'LocalStorageService'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.


what does work is:

import { LocalStorage  } from 'angular-web-storage/src/decorator';

so it is something around that, just looking at that code:

https://github.com/cipchk/angular-web-storage/blob/master/lib/src/service.ts#L42

i just wonder where is that localStorage variable thats in the super call is coming from?

**Comment by jcompagner** [comment]
when upgrading to angular 7 i kind of get exactly the same error:

ERROR in angular-web-storage\web-storage.ts(4,2): Error during template compile of 'AngularWebStorageModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

**Comment by cipchk** [comment]
@jcompagner ths report
