### ISSUE TITLE
AOT-Error

### ISSUE THREAD

**Issue by elninotorres** [cipchk/angular-web-storage#6]
When i do an aot compilation the web storage does not work.AngularWebStorageModule'
Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
'NgModule' calls 'ɵmakeDecorator.
Iget an error like this Please provide how to remove this error/
I use angular 5

**Comment by cipchk** [comment]
@elninotorres  you used currently version? Try upgrading to the latest version.
