### ISSUE TITLE
Angular universal + local storage decorator

### ISSUE THREAD

**Issue by jorjun** [cipchk/angular-web-storage#7]
node_modules/angular-web-storage/bundles/ng:/angular-web-storage/src/decorator.ts:55
  return WebStorage(localStorage, key, expiredAt, expiredUnit);
                    ^
ReferenceError: localStorage is not defined

Getting this error from my component, when running my server-side code. 
Client-side the local storage in the component, using the decorator, works fine.
Wondering if this article has a clue to the problem:
https://www.ryadel.com/en/angular-5-use-localstorage-window-document-and-other-browser-types-angular-universal/

**Comment by cipchk** [comment]
I try release `7.0.0-beta.1` version.

I look forward to your further feedback.
